server:
  #应用端口号
  port: 8202

spring:
  #应用名称
  application:
    name: service-cmn

  #环境设置
  profiles:
    active: dev

  #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123

  #返回Json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.31.100 #灵活host地址 home:192.168.31.100 com:192.168.63.100
    port: 6379
    password: 123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  cloud:
    #nacos注册中心地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  #mapper文件路径
  mapper-locations: classpath:com/edu/guohosp/mapper/xml/*.xml
  #开启控制台SQL语句的输出
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

##开启sentinel
#feign:
#  sentinel:
#    enabled: true

