server:
  #应用端口号
  port: 8204

spring:
  #应用名称
  application:
    name: service-msm

  #环境设置
  profiles:
    active: dev

  #返回Json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.31.100 #灵活host地址 home:192.168.31.100 com:192.168.63.100
    port: 6379
    password: 123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  cloud:
    #nacos注册中心地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

